---
security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
zk:
  broker.root: ${zk.brk.root}
store:
  #optional parameter to configure zookeeper-store
  path: ${broker.store.znode:/broker/zookeeper/metadata}
  cluster: ${zk.cluster.url}
  user: ${system.user}
  password: ${system.user.password}
  keytabPath: ${system.user.keytab.path}
cf:
  catalog:
    serviceName: ${cf.catalog.servicename:zookeeper}
    serviceId: ${cf.catalog.serviceid:zookeeper}
    serviceDescription: ZOOKEEPER service for creating znodes on hadoop distributed coordination service
    baseId: ${BASE_GUID:}
    plans:
      - id: shared-plan
        name: shared
        description: shared
        free: true
    metadata:
      imageUrl: ${IMAGE_URL:}