---
security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
zk:
  broker.root: ${zk.brk.root}
store:
  #optional parameter to configure zookeeper-store
  path: ${broker.store.znode:/broker/zookeeper/metadata}
  cluster: ${zk.cluster.url}
  user: ${system.user}
  password: ${system.user.password}
  keytabPath: ${system.user.keytab.path}
cf:
  catalog:
    serviceName: ${cf.catalog.servicename:zookeeper}
    serviceId: ${cf.catalog.serviceid:zookeeper}
    serviceDescription: ZOOKEEPER service for creating znodes on hadoop distributed coordination service
    baseId: ${BASE_GUID:}
    plans:
      - id: standard-plan
        name: standard
        description: Creates new znode (within organization access space) and returns connection config data
        free: true
    metadata:
      imageUrl: ${IMAGE_URL:}

endpoints.enabled: false
endpoints.health.enabled: true
endpoints.info.enabled: true
endpoints.info.sensitive: false

# http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info-git
management:
  info:
    git:
      mode: full

# http://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html#howto-build-info
info:
  name: "@project.artifactId@"
  app_version: "@project.version@"
  build:
    group: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    time: "@build.time@"
